//
//  Workspace.swift
//  Tuist
//
//  Created by 윤해수 on <#mm/dd/yy#>.
//

import ProjectDescription
import DependencyPlugin

let workspace = Workspace(
  name: "TestTemplate",
  projects: {
    var projects: [Path] = []
    
    projects.append(Path("Projects/App/App"))
    projects += App.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }
    
    projects.append(Path("Projects/Feature/Feature"))
    projects += Feature.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }
    
    projects.append(Path("Projects/Shared/Shared"))
    projects += Shared.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }
    
    return projects
  }(),
  additionalFiles: [
    "Xcconfig/**"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant),
    renderMarkdownReadme: true
  ),
)
