//
//  Workspace.swift
//  Tuist
//
//  Created by 윤해수 on <#mm/dd/yy#>.
//

import ProjectDescription
import DependencyPlugin

let workspace = Workspace(
  name: "<#WorkspaceName#>",
  projects: {
    var projects: [Path] = []
    
    projects.append(Path("Projects/App"))
    
    // Feature 루트 모듈을 워크스페이스에 포함합니다.
    projects.append(Path("Projects/Feature/Feature"))
    projects += Feature.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }
    
    // Shared 루트 모듈을 워크스페이스에 포함합니다.
    projects.append(Path("Projects/Shared/Shared"))
    projects += Shared.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }
    
    return projects
  }(),
  additionalFiles: [
    "<#xcconfigFolders#>/**"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .relevant),
    renderMarkdownReadme: true
  ),
)
