import ProjectDescription
import DependencyPlugin

let workspace = Workspace(
  name: "SwiftCICD",
  projects: {
    var projects: [Path] = []

    projects.append(Path("Projects/App/SwiftCICD"))
    projects += App.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }

    projects.append(Path("Projects/Feature/Feature"))
    projects += Feature.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }

    projects.append(Path("Projects/Domain/Domain"))
    projects += Domain.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }

    projects.append(Path("Projects/Core/Core"))
    projects += Core.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }

    projects.append(Path("Projects/Shared/Shared"))
    projects += Shared.allCases.map {
      Path("Projects/\(String(describing: type(of: $0)))/\(String(describing: $0))")
    }

    return projects
  }(),
  additionalFiles: [
    "Xcconfig/**",
    "fastlane/**",
    ".github/**"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all),
    renderMarkdownReadme: true
  )
)
